name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.11.1

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: jhowssilva
        
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images            
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
      
        file: ./
        push: true
    
        tags: jhowssilva/go_ci:${{github.ref_name}}
          
