name: CD

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Getting file
      run: aws ecs describe-task-definition --task-definition Tarefa_Go_Api_Test --query taskDefinition > task-definition.json
      
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: go
        image: jhowssilva/go_ci:main
        environment-variables: |
           HOST=${{ secrets.DBHOST }}
           USER=${{ secrets.DBUSER }}
           PASSWORD=${{ secrets.DBPASSWORD }}
           DBNAME=${{ secrets.DBNAME }}
           DBPORT=${{ secrets.DBPORT }}
           PORT=8000

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Tarefa_Go_Api_Test-service-ow2nenr8
        cluster: API_Go_Test
        wait-for-service-stability: true
